import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import { SectionCard } from "../ui/SectionCard";

function getChartColors() {
  const isDark = document.documentElement.getAttribute("data-theme") === "dark";
  return {
    grid: isDark ? "#2a2e3a" : "#e6e7eb",
    axis: isDark ? "#8b909a" : "#60646c",
    cursor: isDark ? "rgba(255, 255, 255, 0.04)" : "rgba(0, 0, 0, 0.03)",
    tooltipBg: isDark ? "#1a1d27" : "#ffffff",
    tooltipBorder: isDark ? "#2a2e3a" : "#e0e1e6",
    tooltipShadow: isDark ? "0 12px 32px rgba(0, 0, 0, 0.4)" : "0 12px 32px rgba(0, 0, 0, 0.08)",
    barPrimary: isDark ? "#5ba3e6" : "#1c2024",
    barSecondary: isDark ? "#4a5068" : "#b0b4ba",
    barAccent: isDark ? "#9b6dff" : "#0d74ce",
  };
}

export function ComparisonCharts({ metrics }) {
  const colors = getChartColors();

  return (
    <div className="chart-grid">
      <SectionCard
        eyebrow="Performance"
        title="Encryption vs decryption time"
        subtitle="Sample benchmark timings generated by the backend for the same demo message."
      >
        <div className="chart-wrap">
          <ResponsiveContainer width="100%" height={280}>
            <BarChart data={metrics}>
              <CartesianGrid strokeDasharray="3 3" stroke={colors.grid} />
              <XAxis dataKey="label" stroke={colors.axis} tickLine={false} axisLine={false} />
              <YAxis stroke={colors.axis} tickLine={false} axisLine={false} />
              <Tooltip
                cursor={{ fill: colors.cursor }}
                contentStyle={{
                  borderRadius: 16,
                  border: `1px solid ${colors.tooltipBorder}`,
                  backgroundColor: colors.tooltipBg,
                  boxShadow: colors.tooltipShadow,
                }}
              />
              <Legend />
              <Bar dataKey="encryption_time_ms" fill={colors.barPrimary} radius={[12, 12, 0, 0]} />
              <Bar dataKey="decryption_time_ms" fill={colors.barSecondary} radius={[12, 12, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </SectionCard>

      <SectionCard
        eyebrow="Ciphertext size"
        title="Output length comparison"
        subtitle="Ciphertext size for the same sample message."
      >
        <div className="chart-wrap">
          <ResponsiveContainer width="100%" height={280}>
            <BarChart data={metrics}>
              <CartesianGrid strokeDasharray="3 3" stroke={colors.grid} />
              <XAxis dataKey="label" stroke={colors.axis} tickLine={false} axisLine={false} />
              <YAxis stroke={colors.axis} tickLine={false} axisLine={false} />
              <Tooltip
                cursor={{ fill: colors.cursor }}
                contentStyle={{
                  borderRadius: 16,
                  border: `1px solid ${colors.tooltipBorder}`,
                  backgroundColor: colors.tooltipBg,
                  boxShadow: colors.tooltipShadow,
                }}
              />
              <Bar dataKey="output_length" fill={colors.barAccent} radius={[12, 12, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </SectionCard>
    </div>
  );
}
